spring.application.name=patient-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-patient}:5432/db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=4000
logging.level.root=info